// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: command_id.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cmd.ID {

  /// <summary>Holder for reflection information generated from command_id.proto</summary>
  public static partial class CommandIdReflection {

    #region Descriptor
    /// <summary>File descriptor for command_id.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBjb21tYW5kX2lkLnByb3RvEgZDbWQuSUQqlwMKA0NNRBILCgdJbnZhaWxk",
            "EAASEQoMSGVhcnRCZWF0UmVxEOgHEhEKDEhlYXJ0QmVhdFJzcBDpBxISCg1D",
            "cmVhdGVSb29tUmVxENAPEhIKDUNyZWF0ZVJvb21Sc3AQ0Q8SEQoMTGVhdmVS",
            "b29tUmVxENIPEhEKDExlYXZlUm9vbVJzcBDTDxIZChRVcGRhdGVSb29tSW5m",
            "b05vdGljZRDUDxIQCgtSb29tTGlzdFJlcRDVDxIQCgtSb29tTGlzdFJzcBDW",
            "DxIQCgtKb2luUm9vbVJlcRDXDxIQCgtKb2luUm9vbVJzcBDYDxIRCgxFbnRl",
            "ckdhbWVSZXEQuBcSEQoMRW50ZXJHYW1lUnNwELkXEhEKDFN0YXJ0R2FtZVJl",
            "cRC6FxIRCgxTdGFydEdhbWVSc3AQuxcSEQoMRnJhbWVTeW5jTWluEJBOEhMK",
            "DkZyYW1lVHJhbnNwb25kEJFOEhYKEVdhclNlcXVlbmNlTm90aWNlEJJOEgwK",
            "B1dhck1vdmUQk04SEgoMRnJhbWVTeW5jTWF4EKCcAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cmd.ID.CMD), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CMD {
    /// <summary>
    /// 无效的CMD
    /// </summary>
    [pbr::OriginalName("Invaild")] Invaild = 0,
    /// <summary>
    /// 心跳
    /// </summary>
    [pbr::OriginalName("HeartBeatReq")] HeartBeatReq = 1000,
    [pbr::OriginalName("HeartBeatRsp")] HeartBeatRsp = 1001,
    /// <summary>
    ///=====================房间========================
    ///创建房间
    /// </summary>
    [pbr::OriginalName("CreateRoomReq")] CreateRoomReq = 2000,
    [pbr::OriginalName("CreateRoomRsp")] CreateRoomRsp = 2001,
    /// <summary>
    ///离开房间
    /// </summary>
    [pbr::OriginalName("LeaveRoomReq")] LeaveRoomReq = 2002,
    [pbr::OriginalName("LeaveRoomRsp")] LeaveRoomRsp = 2003,
    /// <summary>
    ///房间信息更新，有人加入，有人离开
    /// </summary>
    [pbr::OriginalName("UpdateRoomInfoNotice")] UpdateRoomInfoNotice = 2004,
    /// <summary>
    ///获取房间列表
    /// </summary>
    [pbr::OriginalName("RoomListReq")] RoomListReq = 2005,
    [pbr::OriginalName("RoomListRsp")] RoomListRsp = 2006,
    /// <summary>
    ///加入房间
    /// </summary>
    [pbr::OriginalName("JoinRoomReq")] JoinRoomReq = 2007,
    [pbr::OriginalName("JoinRoomRsp")] JoinRoomRsp = 2008,
    /// <summary>
    ///=====================房间========================
    ///=====================战斗========================
    ///进入游戏
    /// </summary>
    [pbr::OriginalName("EnterGameReq")] EnterGameReq = 3000,
    [pbr::OriginalName("EnterGameRsp")] EnterGameRsp = 3001,
    /// <summary>
    ///资源加载完毕，开始游戏
    /// </summary>
    [pbr::OriginalName("StartGameReq")] StartGameReq = 3002,
    [pbr::OriginalName("StartGameRsp")] StartGameRsp = 3003,
    /// <summary>
    ///=====================战斗========================
    ///=====================帧同步信息========================
    ///帧数据同步最小值
    /// </summary>
    [pbr::OriginalName("FrameSyncMin")] FrameSyncMin = 10000,
    /// <summary>
    ///帧转发函数
    /// </summary>
    [pbr::OriginalName("FrameTranspond")] FrameTranspond = 10001,
    /// <summary>
    ///同步帧信息
    /// </summary>
    [pbr::OriginalName("WarSequenceNotice")] WarSequenceNotice = 10002,
    /// <summary>
    ///移动请求
    /// </summary>
    [pbr::OriginalName("WarMove")] WarMove = 10003,
    /// <summary>
    ///帧同步最大值
    /// </summary>
    [pbr::OriginalName("FrameSyncMax")] FrameSyncMax = 20000,
  }

  #endregion

}

#endregion Designer generated code
