//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: command_protocol_war.proto
// Note: requires additional types generated from: command_protocol_common.proto
namespace PROTOCOL_WAR
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_ENTER_GAME_REQ")]
  public partial class CMD_ENTER_GAME_REQ : global::ProtoBuf.IExtensible
  {
    public CMD_ENTER_GAME_REQ() {}
    
    private PROTOCOL_COMMON.pre_battle_data _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PROTOCOL_COMMON.pre_battle_data data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_ENTER_GAME_RSP")]
  public partial class CMD_ENTER_GAME_RSP : global::ProtoBuf.IExtensible
  {
    public CMD_ENTER_GAME_RSP() {}
    
    private PROTOCOL_COMMON.pre_battle_data _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PROTOCOL_COMMON.pre_battle_data data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_START_GAME_REQ")]
  public partial class CMD_START_GAME_REQ : global::ProtoBuf.IExtensible
  {
    public CMD_START_GAME_REQ() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_START_GAME_RSP")]
  public partial class CMD_START_GAME_RSP : global::ProtoBuf.IExtensible
  {
    public CMD_START_GAME_RSP() {}
    
    private PROTOCOL_COMMON.RoomInfo _room_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PROTOCOL_COMMON.RoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_WAR_MOVE")]
  public partial class CMD_WAR_MOVE : global::ProtoBuf.IExtensible
  {
    public CMD_WAR_MOVE() {}
    
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private float _move_x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"move_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float move_x
    {
      get { return _move_x; }
      set { _move_x = value; }
    }
    private float _move_y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"move_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float move_y
    {
      get { return _move_y; }
      set { _move_y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_WAR_SEQUENCE_NOTICE")]
  public partial class CMD_WAR_SEQUENCE_NOTICE : global::ProtoBuf.IExtensible
  {
    public CMD_WAR_SEQUENCE_NOTICE() {}
    
    private int _sequence = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}